---
- import_playbook: tomcat.yml

- name: copy war
  hosts: all
  become: yes
  vars:
    source : webapp/target/webapp.war
    destination : /usr/local/apache-tomcat-10.0.14/webapps/
  tasks:
   - name: copy
     copy:
       src: "{{ source }}"
       dest: "{{ destination }}"


  handlers:
    - name: restart tomcat service
      service:
        name: tomcat
        state: restarted
