---
- import_playbook: tomcat.yml

- name: copy war
  hosts: all
  become: yes
  vars:
    source : webapp/target/webapp.war
    destination : /opt/tomcat/latest/webapps/
  tasks:
   - name: copy
     copy:
       src: "{{soucre}}"
       dest: "{{destination}}"


  handlers:
    - name: restart tomcat service
      service:
        name: tomcat
        state: restarted
