---
- name: copy war
hosta: all
become: yes
vars:
  source=./webapp/target/webapp.war
  destination=/var/
tasks:
  - name: install tomcat
    import_tasks: tomcat.yml 
  -name: copy
   copy:
    -src: "{{soucre}}"
    -dest: "{{destination}}"
