---
- name: install tomcat 10
  hosts: all
  become: true

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: telecharge package
    get_url:
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.44/bin/apache-tomcat-10.0.14.tar.gz
      dest: /usr/local

  - name: extract
    unarchive:
      src: /usr/local/apache-tomcat-10.0.14.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start le service tomcat
    shell: nohup /usr/local/apache-tomcat-10.0.14/bin/startup.sh
